#!/bin/bash
source config

# find and mount hard drive, assumes that it has been configured with setup_usb/create
if lsblk | grep -q "$drive_name";
then
	echo "drive found"
	if lsblk | grep -q "$drive_path";
	then
		echo "$drive_name already mounted"
	else
		echo "$drive_name not mounted, mounting"
		./setup_usb /dev/$drive_name mount
	fi
else
	echo "drive not found"
fi

if $enable_wireless;
then
	./setup_wireless
fi

# main loop, iterate through each script in utils directory
#./utils/wifi_quality.py
#./utils/netdiscover.py
#./utils/lldp.py
#./utils/wifi_auth.py "Outside Open" "cylonbase4starswar"
#./utils/speedtest.py
./utils/dhcp.py

# test web API -- cheap and dirty method, use "ps -a | grep -c main" to see how many times main has looped
#./post_database.py
#rm /media/USBDrive/hydrant.db
#./main
