#!/bin/bash

echo 'operating on drive: ' $1
echo 'operation: ' $2

# encrypt drive and setup filesystem

if [ "$2" == "create" ]
then
	sudo shred -v -n 1 $1						# securely erase drive
	dd if=/dev/urandom of=$PWD/luks_key bs=512 count=8		# create encryption key to unlock drive
	sudo cryptsetup luksFormat $1 --key-file=$PWD/luks_key		# initialize luks partition
	sudo cryptsetup luksOpen $1 USBDrive --key-file=$PWD/luks_key	# open luks partition
	sudo mkfs -t ext4 /dev/mapper/USBDrive				# create filesystem
	sudo mkdir /media/USBDrive					# create mountpoint
	sudo chown $USER /media/USBDrive				# change ownership of mountpoint
	sudo mount /dev/mapper/USBDrive /media/USBDrive			# mount drive to mountpoint
elif [ "$2" == "mount" ]
then
	sudo cryptsetup luksOpen $1 USBDrive --key-file=$PWD/luks_key	# open luks partition
	sudo mount /dev/mapper/USBDrive /media/USBDrive			# mount drive to mountpoint
elif [ "$2" == "unmount" ]
then
	sudo umount /media/USBDrive					# unmount from mountpoint
	sudo cryptsetup luksClose USBDrive				# close luks partition
else
	echo "No valid positional argument"
	echo "use: create, mount, unmount"
fi

