#!/bin/bash
source config

interface_name=$(iwconfig 2>&1 | grep -v "no wireless extensions" | grep -oP "^\w+")	# finds names of wireless interfaces, if there are multiple interfaces the variable will act as an array

activated_interface_name=$(ifconfig | grep -oP "^\w+")		# finds names of currently activated interfaces

array_contains () { 
    local array=$1[@]
    local seeking=$2
    local in=0
    for element in ${!array}; do
        if [[ $element == $seeking ]]; then
            in=1
            break
        fi
    done
    return $in
}

for NAME in ${interface_name[@]}
do	
	if array_contains activated_interface_name $NAME; then
		echo "$NAME is not activated, activating"
		sudo ifconfig $NAME up
	else
		echo "$NAME is activated"
	fi
done

