#!/bin/bash

drive_name="sda"		# can find using lsblk
drive_path="/media/USBDrive"	# mountpoint for the drive

db_name="hydrant.db"	# name of sqlite3 database, located on USB drive

api_client_port=65432		# Standard loopback interface address (localhost)
api_client_host="127.0.0.1"	# Port to listen on (non-privileged ports are > 1023)

export db_name		# export so Python can load the database
export drive_path	# ^^
export api_client_host	# ^^
export api_client_port	# ^^

enable_wireless=true	# enable use of wireless interfaces
