---

# Digital Hydrant 2020
# wireless_network_credentials.yml contains list of wireless networks and correspoding credentials
# information is availble to use in collectors

networks:
        - essid : Outside Open
          passwd : cylonbase4starswar

