#!/bin/bash
source config

# hydrant utility, search for nearby wireless accesspoints
# script will run through once, and store gathered data in the database
# command utility to scrape: sudo iwlist wlan0 scanning | egrep 'Cell |Encryption|Quality|Last beacon|ESSID'

table_name="wifi_quality"

# verify that table exits
if sqlite3 $drive_path/$db_name "SELECT name FROM sqlite_master WHERE type='table' AND name='$table_name';" | grep -q $table_name;
then
	echo "table exists for $table_name, continuing"
else
	echo "no table exists for $table_name, creating"
#	sqlite3 $drive_path/$db_name "CREATE TABLE $table_name ();"
fi


