---

# Digital Hydrant 2020
# YAML configuration file for managing collectors
# used by scheduler.py to schedule collector execution and load parameters, additional data, etc

# true/false boolean, toggle whether to run utility or not
enabled: true
# 0 == run immediately, specify execution interval in seconds
exec_time: 0
# -1 == run indefinitely, not required for most collectors
exec_duration: -1
# tell the scheduler if wireless is utilized by this collector
wireless: false

# interface to use
interface: "eth0"
